// Code generated by gogen; DO NOT EDIT.
package example

import (
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/trace"

	"github.com/vladimirkorzhenevskiy/gogen/pkg/log"
)

type Config struct {
	Host string `envconfig:"HOST" required:"true" default:"localhost"`
	Port uint8  `envconfig:"PORT" required:"true" default:"8080"`
}

type Repository struct {
	cfg    Config
	logger *log.Logger
	tracer trace.Tracer
	cache  Cache
	client Client
}

func New(cfg Config) (*Repository, error) {
	return &Repository{
		cfg:    cfg,
		logger: log.Nop(),
		tracer: otel.GetTracerProvider().Tracer("github.com/vladimirkorzhenevskiy/gogen"),
	}, nil
}

func (r *Repository) WithLogger(logger *log.Logger) {
	r.logger = logger
}

func (r *Repository) WithTracer(tracer trace.Tracer) {
	r.tracer = tracer
}

func (r *Repository) WithCache(cache Cache) {
	r.cache = cache
}

func (r *Repository) WithClient(client Client) {
	r.client = client
}
