// Code generated by gogen; DO NOT EDIT.
package example

import (
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/trace"

	"github.com/vladimirkorzhenevskiy/gogen/pkg/log"
)

type Config struct {
	Host string `envconfig:"HOST" required:"true" default:"localhost"`
	Port uint8  `envconfig:"PORT" required:"true" default:"8080"`
}

type UseCase struct {
	cfg    Config
	logger *log.Logger
	tracer trace.Tracer
	cache  Cache
	client Client
}

func New(cfg Config) (*UseCase, error) {
	return &UseCase{
		cfg:    cfg,
		logger: log.Nop(),
		tracer: otel.GetTracerProvider().Tracer("github.com/vladimirkorzhenevskiy/gogen"),
	}, nil
}

func (u *UseCase) WithLogger(logger *log.Logger) {
	u.logger = logger
}

func (u *UseCase) WithTracer(tracer trace.Tracer) {
	u.tracer = tracer
}

func (u *UseCase) WithCache(cache Cache) {
	u.cache = cache
}

func (u *UseCase) WithClient(client Client) {
	u.client = client
}
