// Code generated by gogen; DO NOT EDIT.
package example

import (
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/trace"

	"github.com/vladimirkorzhenevskiy/gogen/pkg/log"
)

type Config struct {
	Host string
	Port uint16
}

type Controller struct {
	cfg    Config
	logger *log.Logger
	tracer trace.Tracer
	cache  Cache
	client Client
}

func New(cfg Config) (*Controller, error) {
	return &Controller{
		cfg:    cfg,
		logger: log.Nop(),
		tracer: otel.GetTracerProvider().Tracer("github.com/vladimirkorzhenevskiy/gogen"),
	}, nil
}

func (c *Controller) WithLogger(logger *log.Logger) {
	c.logger = logger
}

func (c *Controller) WithTracer(tracer trace.Tracer) {
	c.tracer = tracer
}

func (c *Controller) WithCache(cache Cache) {
	c.cache = cache
}

func (c *Controller) WithClient(client Client) {
	c.client = client
}
