// Code generated by gogen; DO NOT EDIT.
package example

import (
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/trace"

	"github.com/vladimirkorzhenevskiy/gogen/pkg/log"
)

type Config struct {
	Host string
	Port uint8
}

type Middleware struct {
	cfg    Config
	logger *log.Logger
	tracer trace.Tracer
	cache  Cache
	client Client
}

func New(cfg Config) (*Middleware, error) {
	return &Middleware{
		cfg:    cfg,
		logger: log.Nop(),
		tracer: otel.GetTracerProvider().Tracer("github.com/vladimirkorzhenevskiy/gogen"),
	}, nil
}

func (m *Middleware) WithLogger(logger *log.Logger) {
	m.logger = logger
}

func (m *Middleware) WithTracer(tracer trace.Tracer) {
	m.tracer = tracer
}

func (m *Middleware) WithCache(cache Cache) {
	m.cache = cache
}

func (m *Middleware) WithClient(client Client) {
	m.client = client
}
