// Code generated by gogen; DO NOT EDIT.
package example

import (
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/trace"

	"github.com/vladimirkorzhenevskiy/gogen/pkg/log"
)

type Config struct {
	Host string `envconfig:"HOST" required:"true" default:"localhost"`
	Port uint8  `envconfig:"PORT" required:"true" default:"8080"`
}

type Adapter struct {
	cfg    Config
	logger *log.Logger
	tracer trace.Tracer
	cache  Cache
	client Client
}

func New(cfg Config) (*Adapter, error) {
	return &Adapter{
		cfg:    cfg,
		logger: log.Nop(),
		tracer: otel.GetTracerProvider().Tracer("github.com/vladimirkorzhenevskiy/gogen"),
	}, nil
}

func (a *Adapter) WithLogger(logger *log.Logger) {
	a.logger = logger
}

func (a *Adapter) WithTracer(tracer trace.Tracer) {
	a.tracer = tracer
}

func (a *Adapter) WithCache(cache Cache) {
	a.cache = cache
}

func (a *Adapter) WithClient(client Client) {
	a.client = client
}
